import type { ModuleSeed } from '../types';

export const desafioFinal: ModuleSeed = {
  slug: 'desafio-final',
  title: 'Módulo 20 — Desafio Final',
  stage: 'Projeto',
  description: 'Projeto integrador: rede completa de uma empresa com matriz e filial — VLSM, VLANs, inter-VLAN, DHCP, DNS, NAT, firewall, VPN e SSH — mais a prova final.',
  accent: 'from-yellow-400 to-red-500',
  objective: 'Aplicar todos os conceitos do curso para projetar, configurar, testar e documentar a rede de uma empresa real.',
  summary: 'Você é o analista de redes da NetLearn Ltda. Sua missão é entregar a rede da matriz e da filial funcionando, segura e documentada — e depois provar seu conhecimento na prova final de 20 questões.',
  lessons: [
    {
      slug: 'enunciado-do-desafio',
      title: 'Enunciado e requisitos',
      introduction: 'A NetLearn Ltda. está inaugurando sua matriz e uma filial. A matriz tem os setores Vendas, TI e RH, uma sala de servidores e Wi-Fi para visitantes. A filial tem uma equipe comercial. Você recebeu o bloco 10.10.0.0/23 para a matriz e 10.10.2.0/27 para a filial.',
      why_it_matters: 'Projetos reais exigem combinar tudo: endereçamento, switching, roteamento, serviços e segurança. É exatamente o tipo de tarefa cobrado em entrevistas técnicas e certificações.',
      real_world: 'Este cenário reproduz, em escala reduzida, a rede de uma pequena empresa: segmentação por setor, serviços centralizados, publicação de um site e interligação de filial via Internet.',
      explanation: 'Trabalhe em etapas, testando cada uma antes de seguir: (1) endereçamento, (2) VLANs e trunks, (3) roteamento inter-VLAN, (4) DHCP e DNS, (5) NAT e acesso à Internet, (6) firewall/ACLs, (7) VPN com a filial, (8) gerência via SSH, (9) testes e documentação.',
      exercise: 'Antes de configurar qualquer equipamento, qual é o primeiro artefato que você deve produzir?',
      exercise_answer: 'O plano de endereçamento (tabela de VLANs, sub-redes, gateways e IPs fixos) junto com o diagrama da topologia. Todas as configurações dependem dele.',
      challenge: 'Entregue a rede completa funcionando no Packet Tracer (ou GNS3/EVE-NG) atendendo a todos os requisitos e acompanhada da documentação.',
      keywords: ['projeto', 'VLSM', 'VLAN', 'inter-VLAN', 'DHCP', 'DNS', 'NAT', 'ACL', 'VPN', 'SSH'],
      sections: [
        {
          title: 'Topologia',
          code: '                     Internet (ISP)\n            203.0.113.1/30        198.51.100.1/30\n                 │                       │\n   203.0.113.2  R1-MATRIZ ══ VPN IPsec ══ R2-FILIAL  198.51.100.2\n                 │ trunk (subinterfaces)      │\n               SW-CORE ─── SW-ACESSO        SW-FILIAL\n          (VLANs 10,20,30,40,50,99)         (LAN 10.10.2.0/27)\n     Vendas · TI · RH · Visitantes · Servidores',
        },
        {
          title: 'Requisitos',
          steps: [
            'R1 — Endereçamento com VLSM a partir de 10.10.0.0/23, sem sobreposição, para: Vendas 100 hosts, Visitantes 100, TI 50, RH 20, Servidores 10 e Gerência 10.',
            'R2 — Uma VLAN por setor (10 Vendas, 20 TI, 30 RH, 40 Visitantes, 50 Servidores, 99 Gerência), VLAN nativa 999 sem uso e portas não utilizadas desativadas.',
            'R3 — Roteamento entre VLANs no R1 (router-on-a-stick) ou no SW-CORE (SVIs).',
            'R4 — DHCP para Vendas, TI, RH, Visitantes e Filial, excluindo gateways e IPs fixos.',
            'R5 — Servidor DNS interno (10.10.1.98) resolvendo intranet.netlearn.local para o servidor web 10.10.1.99.',
            'R6 — Acesso à Internet para todas as VLANs via PAT na interface WAN do R1.',
            'R7 — Servidor web publicado na Internet via NAT estático na porta 443.',
            'R8 — ACLs: Visitantes só acessam a Internet (nada interno); somente TI acessa a VLAN de Gerência; RH não é acessível por Vendas.',
            'R9 — VPN site-to-site IPsec entre R1 e R2 para as redes da matriz e 10.10.2.0/27.',
            'R10 — Gerência de todos os equipamentos apenas por SSH v2, com usuário local, a partir da VLAN de TI.',
          ],
        },
        {
          title: 'Rubrica de avaliação (100 pontos)',
          table: {
            headers: ['Critério', 'Pontos', 'Como verificar'],
            rows: [
              ['Plano de endereçamento correto (VLSM, sem sobreposição)', '15', 'Tabela entregue'],
              ['VLANs, trunks e segurança de portas', '10', 'show vlan brief, show interfaces trunk'],
              ['Roteamento inter-VLAN', '10', 'ping entre VLANs permitidas'],
              ['DHCP funcionando em todas as redes de usuários', '10', 'PCs recebem IP correto'],
              ['DNS interno', '5', 'nslookup intranet.netlearn.local'],
              ['PAT e NAT estático', '10', 'show ip nat translations'],
              ['ACLs conforme requisito R8', '15', 'Testes positivos e negativos'],
              ['VPN site-to-site', '15', 'ping matriz ↔ filial; show crypto ipsec sa'],
              ['Gerência por SSH', '5', 'Telnet recusado, SSH aceito'],
              ['Documentação (diagrama, tabela, evidências)', '5', 'Relatório'],
            ],
          },
        },
      ],
    },
    {
      slug: 'verificacao-e-solucao',
      title: 'Verificação, dicas e solução de referência',
      introduction: 'Um projeto só está pronto quando foi testado. Use o checklist abaixo para validar cada requisito, consulte as dicas apenas se travar e compare seu resultado com a solução de referência no final.',
      why_it_matters: 'Testes negativos (o que deve ser bloqueado continua bloqueado) são tão importantes quanto os positivos: uma ACL que "funciona" porque libera tudo é uma falha de segurança.',
      real_world: 'Em projetos reais, essa etapa vira o "relatório de aceite": a lista de testes executados, com evidências, que o cliente assina antes de a rede entrar em produção.',
      explanation: 'Teste de baixo para cima: interfaces e VLANs, depois IP e gateway, roteamento, serviços (DHCP/DNS), NAT, ACLs e por fim a VPN. Quando algo falhar, volte uma camada.',
      exercise: 'Um PC da VLAN de Visitantes consegue pingar o servidor 10.10.1.99. Qual requisito está sendo violado e onde você corrigiria?',
      exercise_answer: 'O R8: visitantes não podem acessar nada interno. Corrija com uma ACL estendida aplicada na entrada da subinterface/SVI da VLAN 40, negando destinos 10.10.0.0/16 (redes internas) e permitindo o restante.',
      challenge: 'Escreva o relatório de aceite com pelo menos 15 testes (positivos e negativos), o comando usado e o resultado obtido.',
      keywords: ['checklist', 'testes', 'troubleshooting', 'documentação', 'solução'],
      sections: [
        {
          title: 'Checklist de verificação',
          items: [
            'PCs de cada VLAN recebem IP da sub-rede correta (ipconfig).',
            'Ping do PC de Vendas para o gateway da VLAN 10.',
            'Ping de TI para Vendas e RH (permitido).',
            'Ping de Vendas para RH (deve falhar).',
            'Ping de Visitantes para 10.10.1.99 (deve falhar) e para o "servidor da Internet" (deve funcionar).',
            'nslookup intranet.netlearn.local retorna 10.10.1.99.',
            'Navegador de um PC interno abre https://intranet.netlearn.local.',
            'Host da Internet acessa 203.0.113.2:443 (NAT estático).',
            'show ip nat translations exibe várias traduções PAT.',
            'Ping de um PC da filial para um PC de TI na matriz (via VPN).',
            'show crypto ipsec sa com contadores encaps/decaps aumentando.',
            'SSH para o SW-CORE a partir de TI funciona; a partir de Vendas falha; Telnet sempre falha.',
          ],
        },
        {
          title: 'Dica 1 — Plano de endereçamento',
          collapsed: true,
          content: 'Ordene da maior para a menor rede: Vendas (/25), Visitantes (/25), TI (/26), RH (/27), Servidores (/28), Gerência (/28). Comece em 10.10.0.0 e aloque cada bloco no próximo múltiplo do seu tamanho.',
        },
        {
          title: 'Dica 2 — ACLs',
          collapsed: true,
          content: 'Aplique ACLs estendidas na ENTRADA da interface da VLAN de origem. Para Visitantes: deny ip 10.10.0.128 0.0.0.127 10.10.0.0 0.0.255.255 seguido de permit ip any any. Lembre do deny implícito no final. Como o DNS interno ficará inacessível para Visitantes, entregue um DNS público (ex.: 8.8.8.8) no pool DHCP dessa VLAN.',
        },
        {
          title: 'Dica 3 — VPN e NAT',
          collapsed: true,
          content: 'O tráfego matriz → filial não pode ser traduzido pelo PAT, senão não casa com a ACL "interessante" da VPN. Na ACL do NAT, negue primeiro o tráfego 10.10.0.0/23 → 10.10.2.0/27 e só então permita o restante.',
        },
        {
          title: 'Solução de referência — endereçamento',
          collapsed: true,
          table: {
            headers: ['VLAN / Rede', 'Sub-rede', 'Gateway', 'Faixa DHCP / IPs fixos', 'Broadcast'],
            rows: [
              ['10 Vendas', '10.10.0.0/25', '10.10.0.1', '.11 – .126', '10.10.0.127'],
              ['40 Visitantes', '10.10.0.128/25', '10.10.0.129', '.139 – .254', '10.10.0.255'],
              ['20 TI', '10.10.1.0/26', '10.10.1.1', '.11 – .62', '10.10.1.63'],
              ['30 RH', '10.10.1.64/27', '10.10.1.65', '.75 – .94', '10.10.1.95'],
              ['50 Servidores', '10.10.1.96/28', '10.10.1.97', 'DNS .98, Web .99 (fixos)', '10.10.1.111'],
              ['99 Gerência', '10.10.1.112/28', '10.10.1.113', 'SW-CORE .114, SW-ACESSO .115', '10.10.1.127'],
              ['Filial', '10.10.2.0/27', '10.10.2.1', '.11 – .30', '10.10.2.31'],
              ['WAN Matriz', '203.0.113.0/30', '203.0.113.1 (ISP)', 'R1 = .2', '203.0.113.3'],
              ['WAN Filial', '198.51.100.0/30', '198.51.100.1 (ISP)', 'R2 = .2', '198.51.100.3'],
            ],
          },
        },
        {
          title: 'Solução de referência — trechos de configuração do R1',
          collapsed: true,
          code: 'interface g0/0.10\n encapsulation dot1Q 10\n ip address 10.10.0.1 255.255.255.128\n ip nat inside\ninterface g0/0.40\n encapsulation dot1Q 40\n ip address 10.10.0.129 255.255.255.128\n ip nat inside\n ip access-group VISITANTES in\n!\nip dhcp excluded-address 10.10.0.1 10.10.0.10\nip dhcp pool VENDAS\n network 10.10.0.0 255.255.255.128\n default-router 10.10.0.1\n dns-server 10.10.1.98\n!\nip access-list extended VISITANTES\n deny   ip 10.10.0.128 0.0.0.127 10.10.0.0 0.0.255.255\n permit ip any any\n!\nip access-list extended NAT\n deny   ip 10.10.0.0 0.0.1.255 10.10.2.0 0.0.0.31\n permit ip 10.10.0.0 0.0.1.255 any\nip nat inside source list NAT interface g0/1 overload\nip nat inside source static tcp 10.10.1.99 443 203.0.113.2 443\n!\ncrypto isakmp policy 10\n encryption aes 256\n hash sha256\n authentication pre-share\n group 14\ncrypto isakmp key ChaveForte! address 198.51.100.2\ncrypto ipsec transform-set TS esp-aes 256 esp-sha256-hmac\nip access-list extended VPN-FILIAL\n permit ip 10.10.0.0 0.0.1.255 10.10.2.0 0.0.0.31\ncrypto map VPN 10 ipsec-isakmp\n set peer 198.51.100.2\n set transform-set TS\n match address VPN-FILIAL\ninterface g0/1\n ip address 203.0.113.2 255.255.255.252\n ip nat outside\n crypto map VPN\nip route 0.0.0.0 0.0.0.0 203.0.113.1',
        },
      ],
    },
  ],
  quizQuestions: [
    { question: 'Em qual camada do OSI atua o roteador?', options: ['Camada 1', 'Camada 2', 'Camada 3', 'Camada 4'], answer: 'Camada 3', explanation: 'O roteador encaminha pacotes pelo endereço IP.' },
    { question: 'Qual a PDU da camada de Transporte quando se usa TCP?', options: ['Quadro', 'Pacote', 'Segmento', 'Bit'], answer: 'Segmento', explanation: 'TCP → segmento; UDP → datagrama.' },
    { question: 'Quantas camadas tem o modelo TCP/IP clássico?', options: ['4', '5', '6', '7'], answer: '4', explanation: 'Acesso à Rede, Internet, Transporte e Aplicação.' },
    { question: 'Qual destes é um endereço IPv4 privado?', options: ['11.0.0.1', '172.15.0.1', '192.168.50.4', '100.200.1.1'], answer: '192.168.50.4', explanation: '192.168.0.0/16 é privado (RFC 1918).' },
    { question: 'Qual o broadcast da rede 10.10.1.64/27?', options: ['10.10.1.95', '10.10.1.127', '10.10.1.79', '10.10.1.63'], answer: '10.10.1.95', explanation: 'Bloco de 32: .64 a .95.' },
    { question: 'Qual prefixo comporta 100 hosts com o menor desperdício?', options: ['/24', '/25', '/26', '/27'], answer: '/25', explanation: '/25 = 126 hosts; /26 = 62.' },
    { question: 'O ARP Reply é enviado em:', options: ['Broadcast', 'Unicast', 'Multicast', 'Anycast'], answer: 'Unicast', explanation: 'O Request é broadcast; o Reply vai direto a quem perguntou.' },
    { question: 'Qual protocolo de transporte é usado por VoIP e jogos online?', options: ['TCP', 'UDP', 'ICMP', 'ARP'], answer: 'UDP', explanation: 'Baixa latência importa mais que retransmissão.' },
    { question: 'Qual a porta padrão do DNS?', options: ['25', '53', '67', '123'], answer: '53', explanation: 'DNS usa a porta 53, principalmente em UDP.' },
    { question: 'Qual registro DNS aponta para o servidor de e-mail?', options: ['A', 'MX', 'PTR', 'CNAME'], answer: 'MX', explanation: 'Mail eXchanger.' },
    { question: 'Qual a ordem correta do processo DHCP?', options: ['Request, Offer, Discover, ACK', 'Discover, Offer, Request, ACK', 'Offer, Discover, ACK, Request', 'Discover, Request, Offer, ACK'], answer: 'Discover, Offer, Request, ACK', explanation: 'DORA.' },
    { question: 'Um erro HTTP 404 significa:', options: ['Erro interno do servidor', 'Recurso não encontrado', 'Acesso proibido', 'Redirecionamento'], answer: 'Recurso não encontrado', explanation: '4xx = erro do cliente; 404 = Not Found.' },
    { question: 'Na autenticação SSH por chave, o que vai para o servidor?', options: ['A chave privada', 'A chave pública', 'A senha', 'O known_hosts'], answer: 'A chave pública', explanation: 'Ela fica em ~/.ssh/authorized_keys.' },
    { question: 'O traceroute funciona manipulando qual campo?', options: ['TTL', 'Checksum', 'Porta', 'MAC'], answer: 'TTL', explanation: 'Cada roteador que zera o TTL responde com ICMP Time Exceeded.' },
    { question: 'O que o switch faz com um quadro cujo destino não está na tabela MAC?', options: ['Descarta', 'Flooding', 'Envia ao roteador', 'Devolve à origem'], answer: 'Flooding', explanation: 'Envia por todas as portas da VLAN, exceto a de origem.' },
    { question: 'Qual rota o roteador escolhe quando várias correspondem ao destino?', options: ['A mais antiga', 'A de maior prefixo', 'A de maior métrica', 'A primeira configurada'], answer: 'A de maior prefixo', explanation: 'Longest prefix match.' },
    { question: 'Qual palavra-chave ativa o PAT no Cisco IOS?', options: ['static', 'overload', 'pool', 'masquerade'], answer: 'overload', explanation: 'ip nat inside source list 1 interface g0/1 overload.' },
    { question: 'O que acontece com o tráfego que não corresponde a nenhuma regra de uma ACL Cisco?', options: ['É permitido', 'É negado', 'É registrado e permitido', 'É roteado para a DMZ'], answer: 'É negado', explanation: 'Deny implícito no final de toda ACL.' },
    { question: 'Qual padrão define o trunk de VLANs?', options: ['802.1Q', '802.11ac', '802.3af', '802.1X'], answer: '802.1Q', explanation: 'Tag de 4 bytes com VLAN ID de 12 bits.' },
    { question: 'Qual componente do IPsec cifra os dados do túnel?', options: ['AH', 'IKE', 'ESP', 'GRE'], answer: 'ESP', explanation: 'O ESP oferece confidencialidade; o IKE negocia as chaves.' },
  ],
  details: {
    objectives: [
      'Projetar um plano de endereçamento completo com VLSM.',
      'Implementar VLANs, trunks e roteamento inter-VLAN.',
      'Configurar DHCP, DNS, NAT/PAT e publicação de serviço.',
      'Aplicar ACLs de acordo com uma política de segurança.',
      'Interligar matriz e filial com VPN IPsec e gerenciar tudo por SSH.',
      'Testar, documentar e justificar as decisões de projeto.',
    ],
    keyPoints: [
      'Planeje antes de configurar: diagrama + tabela de endereçamento.',
      'Configure e teste em etapas, de baixo para cima.',
      'Faça testes positivos e negativos.',
      'Documente tudo: é parte da entrega.',
    ],
    commands: [
      { title: 'Comandos de verificação mais usados', platform: 'Cisco IOS', code: 'show ip interface brief\nshow vlan brief\nshow interfaces trunk\nshow ip route\nshow ip dhcp binding\nshow ip nat translations\nshow access-lists\nshow crypto ipsec sa\nshow ip ssh' },
      { title: 'Testes a partir dos PCs', platform: 'Windows', code: 'ipconfig /all\nping 10.10.0.1\nnslookup intranet.netlearn.local\ntracert 10.10.2.11' },
    ],
    pitfalls: [
      { problem: 'Configurar tudo de uma vez e não saber onde está o erro.', solution: 'Valide cada etapa antes de avançar.' },
      { problem: 'VPN não sobe porque o tráfego está sendo traduzido pelo PAT.', solution: 'Exclua o tráfego matriz↔filial da ACL do NAT.' },
      { problem: 'Esquecer o "permit ip any any" no final de ACLs de bloqueio pontual.', solution: 'Lembre do deny implícito.' },
    ],
    security: [
      'Revise o projeto com a mentalidade de um atacante: o que um visitante consegue alcançar?',
      'Senhas fortes e únicas, SSH apenas, VLAN de gerência isolada.',
      'Mantenha backup das configurações finais.',
    ],
    lab: {
      title: 'Entrega do projeto NetLearn Ltda.',
      goal: 'Montar, testar e documentar a rede completa.',
      tools: 'Cisco Packet Tracer (recomendado), GNS3 ou EVE-NG.',
      steps: [
        'Desenhe a topologia e preencha a tabela de endereçamento.',
        'Implemente os requisitos R1 a R10 em ordem, testando cada um.',
        'Execute o checklist de verificação e registre as evidências.',
        'Faça a prova final abaixo e revise os módulos das questões que errar.',
      ],
      expected: 'Rede funcional atendendo aos 10 requisitos, relatório de aceite e nota igual ou superior a 70% na prova final.',
    },
    references: ['Todos os módulos anteriores do NetLearn', 'Cisco Packet Tracer — netacad.com', 'Cisco CCNA 200-301 — tópicos do exame'],
  },
};
